### ISSUE TITLE
Simulation support?

### ISSUE THREAD

**Issue by zxfever** [Hao-Starrr/humanoid-arm-retarget#1]
Does this repo support simulation testing, or its full performance only be tested on real humanoid arms?

Thx

**Comment by Hao-Starrr** [comment]
This retargeting doesn't block the simulation, but yes, it is only tested on real arms. 
You can build with your simulation environment by URDF. We initially teleop franka in simulation. You may find code at https://github.com/Hao-Starrr/franka_enhanced_teleop.
