### ISSUE TITLE
difference between left_wrist and left_forearmWrist

### ISSUE THREAD

**Issue by Loong1512** [Hao-Starrr/humanoid-arm-retarget#5]
Thank you to the author team for your efforts，this is a great work. I encountered some confusion during the implementation and hope to get answers:

1. What is the difference between `left_wrist` and `left_forearmWrist`, especially regarding their rotation directions? I already understand that their relative coordinates are different.

2. I am confused about the second multiplication in this piece of code:
`left_forearmWrist = self.left_base @ left_forearmWrist @ self.left_wrist`
Why isn't it written as `left_wrist @ self.left_wrist` or `left_forearmWrist @ self.left_forearmWrist`?

**Comment by Hao-Starrr** [comment]
Thanks you Loong. 
1. `left_wrist` and `left_forearmWrist`, these naming is from Apple Vision Pro official doc. I have to say it is confusing. `left_wrist` position is at the wrist, orientation is attached to the hand. `forearmWrist `position is also at the wrist, but orientation is attached to the forearm. 
2. The first `left_forearmWrist` means "robot optimization target, which is, what we want to robot arm to be in robot base frame". Then the coordinate is "robot_base_R_robot_wrist = robot_base_R_vr_base @ vr_base_R_human_wrist @ human_wrist_R_robot_wrist".
